services:
  asterisk:
    image: ghcr.io/jackjyq/asterisk:22.8.2_debian-trixie
    container_name: asterisk-hello
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config:/etc/asterisk:ro
    healthcheck:
      test: ["CMD", "asterisk", "-rx", "core show uptime"]
      interval: 30s
      timeout: 10s
      retries: 3
