[from-internal]
; When someone dials 100, answer and play hello-world
exten = 100,1,Answer()
same = n,Wait(1)
same = n,Playback(hello-world)
same = n,Hangup()

; Allow calling between extensions
exten = 6001,1,Dial(PJSIP/6001,20,r)
same = n,Answer()
same = n,Wait(3)
same = n,Hangup()

exten = 6002,1,Dial(PJSIP/6002,20,r)
same = n,Answer()
same = n,Wait(3)
same = n,Hangup()
